s

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -162,12 +162,26 @@ jobs:
     steps:
       - checkout
       - run:
-          name: Install Dependencies
+          name: Install Chrome
+          command: |
+            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
+            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
+            sudo apt-get update
+            sudo apt-get install google-chrome-stable
+      - run:
+          name: Install Dependencies and Run Test
           command: |
             cd /root/project/stagingtest
             pip install -r /root/project/stagingtest/requirements.txt
             pip install pymysql
-            python test_staging.py 
+            TEST_OUTPUT=$(python test_staging.py 2>&1)
+            TEST_EXIT_CODE=$?
+            echo "$TEST_OUTPUT"  # Print the test report
+
+            if [[ $TEST_EXIT_CODE -ne 0 ]]; then
+              echo "Tests failed. Exiting with status $TEST_EXIT_CODE."
+              exit $TEST_EXIT_CODE
+            fi 
 
 workflows:
   build-and-test:
